export const GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID';
export const GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET';
export const GITHUB_GET_USER_INFO_URL = 'GITHUB_GET_USER_INFO_URL';
export const GITHUB_GET_TOKEN_URL = 'GITHUB_GET_TOKEN_URL';
